### YamlMime:PowershellCmdlet
summary: |-
  Adds a strong password to an application.
module: AzureAD
notes: ""
inputs:
- name: <xref href="string" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Open.MSGraph.Model.PasswordCredential" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Open.MSGraph.Model.PasswordCredential" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  New-AzureADMSApplicationPassword -ObjectId <String> -PasswordCredential <PasswordCredential>

   [<CommonParameters>]
examples:
- title: 'Example 1: Add a password to an application'
  code: |-
    PS C:\>New-AzureADMSApplicationPassword -ObjectId 14a3f1ac-46a7-4d00-b1ca-0b2b84f033c2 -PasswordCredential @{ displayname = "mypassword" }

              CustomKeyIdentifier :
              EndDateTime         : 10/28/2021 3:57:37 PM
              DisplayName         :
              KeyId               : 024c4c6e-87c3-4473-8e36-650f16bb730d
              StartDateTime       : 10/28/2019 3:57:37 PM
              SecretText          : EQ:A-s45?Rt9/3Bp?7]-7__IO]3AG09E
              Hint                : EQ:
  description: |-
    This command adds a password to the specified application.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    The unique identifier of the object specific Azure Active Directory object

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="PasswordCredential" data-throw-if-not-resolved="False" />
  name: PasswordCredential
  isRequired: true
  description: |+
    Represents a password credential associated with an application or a service principal.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: AzureAD.New-AzureADMSApplicationPassword
name: New-AzureADMSApplicationPassword
description: |-
  Adds a strong password to an application.
metadata:
  external help file: Microsoft.Open.MS.GraphV10.PowerShell.dll-Help.xml
  Module Name: AzureAD
  online version: ""
  schema: 2.0.0
