### YamlMime:PowershellCmdlet
summary: |-
  {{ Fill in the Synopsis }}
module: AzureAD
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- Remove-AzureADDeletedApplication -ObjectId <String> [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\> {{ Add example code here }}
  description: |-
    {{ Add example description here }}
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    {{ Fill ObjectId Description }}

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: AzureAD.Remove-AzureADDeletedApplication
name: Remove-AzureADDeletedApplication
description: |-
  {{ Fill in the Description }}
metadata:
  external help file: Microsoft.Open.AzureAD16.Graph.PowerShell.dll-Help.xml
  Module Name: AzureAD
  online version: ""
  schema: 2.0.0
