### YamlMime:PowershellCmdlet
summary: |-
  Updates the properties of an application object.
module: AzureAD
notes: ""
inputs:
- name: <xref href="Boolean" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Open.MSGraph.Model.ApiApplication" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Open.MSGraph.Model.InformationalUrl" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Open.MSGraph.Model.OptionalClaims" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Open.MSGraph.Model.ParentalControlSettings" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Open.MSGraph.Model.PublicClientApplication" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Open.MSGraph.Model.WebApplication" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="string" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.MSGraph.Model.AddIn" data-throw-if-not-resolved="False" /><span>]</span>
  description: ""
- name: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.MSGraph.Model.AppRole" data-throw-if-not-resolved="False" /><span>]</span>
  description: ""
- name: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.MSGraph.Model.KeyCredential" data-throw-if-not-resolved="False" /><span>]</span>
  description: ""
- name: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.MSGraph.Model.PasswordCredential" data-throw-if-not-resolved="False" /><span>]</span>
  description: ""
- name: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.MSGraph.Model.RequiredResourceAccess" data-throw-if-not-resolved="False" /><span>]</span>
  description: ""
- name: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="System.String" data-throw-if-not-resolved="False" /><span>]</span>
  description: ""
- name: <xref href="System.Nullable`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="System.Boolean" data-throw-if-not-resolved="False" /><span>]</span>
  description: ""
syntaxes:
- >-
  Set-AzureADMSApplication -ObjectId <String>

   [-AddIns <System.Collections.Generic.List`1[Microsoft.Open.MSGraph.Model.AddIn]>] [-Api <ApiApplication>]

   [-AppRoles <System.Collections.Generic.List`1[Microsoft.Open.MSGraph.Model.AppRole]>]

   [-GroupMembershipClaims <String>] [-IsDeviceOnlyAuthSupported <Boolean>] [-IsFallbackPublicClient <Boolean>]

   [-IdentifierUris <System.Collections.Generic.List`1[System.String]>] [-DisplayName <String>]

   [-InformationalUrl <InformationalUrl>]

   [-KeyCredentials <System.Collections.Generic.List`1[Microsoft.Open.MSGraph.Model.KeyCredential]>]

   [-OptionalClaims <OptionalClaims>] [-ParentalControlSettings <ParentalControlSettings>]

   [-PasswordCredentials <System.Collections.Generic.List`1[Microsoft.Open.MSGraph.Model.PasswordCredential]>]

   [-PublicClient <PublicClientApplication>]

   [-RequiredResourceAccess <System.Collections.Generic.List`1[Microsoft.Open.MSGraph.Model.RequiredResourceAccess]>]

   [-SignInAudience <String>] [-Tags <System.Collections.Generic.List`1[System.String]>]

   [-TokenEncryptionKeyId <String>] [-Web <WebApplication>] [<CommonParameters>]
examples:
- title: 'Example 1: Update an application'
  code: |-
    PS C:\>Set-AzureADMSApplication -ObjectId fcd37fb8-449c-45af-92fc-5448c671fd30 `
              -DisplayName "my name" `
              -AddIns @{ Type = "mytype"; Properties = [PSCustomObject]@{ Key = "key"; Value = "value" } } `
              -Api @{ AcceptMappedClaims = $true } `
              -AppRoles @{ Id = "21111111-1111-1111-1111-111111111111"; DisplayName = "role"; AllowedMemberTypes = "User"; Description = "mydescription"; Value = "myvalue" } `
              -InformationalUrl @{ SupportUrl = "https://mynewapp.contoso.com/support.html" } `
              -IsDeviceOnlyAuthSupported $false `
              -IsFallbackPublicClient $false `
              -KeyCredentials @{ KeyId = "41111111-1111-1111-1111-111111111111"; Usage = "Encrypt"; Key = [System.IO.File]::ReadAllBytes("file.cer"); Type = "AsymmetricX509Cert" } `
              -OptionalClaims @{ IdToken = [PSCustomObject]@{ Name = "claimName"; Source = "claimSource" } } `
              -ParentalControlSettings @{ LegalAgeGroupRule = "Block" } `
              -PublicClient @{ RedirectUris = "https://mynewapp.contoso.com/" } `
              -RequiredResourceAccess @{ ResourceAppId = "31111111-1111-1111-1111-111111111111"; ResourceAccess = [PSCustomObject]@{ Type = "Scope" } } `
              -SignInAudience AzureADandPersonalMicrosoftAccount `
              -Tags "mytag" `
              -TokenEncryptionKeyId "41111111-1111-1111-1111-111111111111" `
              -Web @{ LogoutUrl = "https://mynewapp.contoso.com/logout.html" } `
              -GroupMembershipClaims "SecurityGroup" `
              -IdentifierUris "https://mynewapp.contoso.com"`
              -PasswordCredentials {passwordcredentials}
  description: |-
    This command updates the specified application.
  summary: ""
parameters:
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.MSGraph.Model.AddIn" data-throw-if-not-resolved="False" /><span>]</span>
  name: AddIns
  description: |+
    Defines custom behavior that a consuming service can use to call an app in specific contexts.
    For example, applications that can render file streams may set the addIns property for its "FileHandler" functionality.
    This will let services like Office 365 call the application in the context of a document the user is working on.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="ApiApplication" data-throw-if-not-resolved="False" />
  name: Api
  description: |+
    Specifies settings for an application that implements a web API.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.MSGraph.Model.AppRole" data-throw-if-not-resolved="False" /><span>]</span>
  name: AppRoles
  description: |+
    The collection of application roles that an application may declare.
    These roles can be assigned to users, groups or service principals.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DisplayName
  description: |+
    Specifies the display name.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: GroupMembershipClaims
  description: |+
    Configures the groups claim issued in a user or OAuth 2.0 access token that the application expects.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="System.String" data-throw-if-not-resolved="False" /><span>]</span>
  name: IdentifierUris
  description: |+
    Specifies identifier URIs.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="InformationalUrl" data-throw-if-not-resolved="False" />
  name: InformationalUrl
  description: |+
    Basic profile information of the application such as app's marketing, support, terms of service and privacy statement URLs.
    The terms of service and privacy statement are surfaced to users through the user consent experience.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: IsDeviceOnlyAuthSupported
  description: |+
    Specifies if the application supports authentication using a device token.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: IsFallbackPublicClient
  description: |+
    Specifies the fallback application type as public client, such as an installed application running on a mobile device.
    The default value is false which means the fallback application type is confidential client such as web app.
    There are certain scenarios where Azure AD cannot determine the client application type (e.g.
    ROPC flow where it is configured without specifying a redirect URI).
    In those cases Azure AD will interpret the application type based on the value of this property.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.MSGraph.Model.KeyCredential" data-throw-if-not-resolved="False" /><span>]</span>
  name: KeyCredentials
  description: |+
    Specifies key credentials.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    Specifies the ID of an application in Azure AD.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="OptionalClaims" data-throw-if-not-resolved="False" />
  name: OptionalClaims
  description: |+
    Application developers can configure optional claims in their Azure AD apps to specify which claims they want in tokens sent to their application by the Microsoft security token service.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="ParentalControlSettings" data-throw-if-not-resolved="False" />
  name: ParentalControlSettings
  description: |+
    Specifies parental control settings for an application.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.MSGraph.Model.PasswordCredential" data-throw-if-not-resolved="False" /><span>]</span>
  name: PasswordCredentials
  description: |+
    The collection of password credentials associated with the application

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="PublicClientApplication" data-throw-if-not-resolved="False" />
  name: PublicClient
  description: |+
    Specifies whether this application is a public client (such as an installed application running on a mobile device).
    Default is false.

    Specifies whether this application is a public client (such as an installed application running on a mobile device).
    Default is false.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.MSGraph.Model.RequiredResourceAccess" data-throw-if-not-resolved="False" /><span>]</span>
  name: RequiredResourceAccess
  description: |+
    @{Text=}

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SignInAudience
  description: |+
    Specifies what Microsoft accounts are supported for the current application.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="System.String" data-throw-if-not-resolved="False" /><span>]</span>
  name: Tags
  description: |+
    Custom strings that can be used to categorize and identify the application.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: TokenEncryptionKeyId
  description: |+
    Specifies the keyId of a public key from the keyCredentials collection.
    When configured, Azure AD encrypts all the tokens it emits by using the key this property points to.
    The application code that receives the encrypted token must use the matching private key to decrypt the token before it can be used for the signed-in user.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="WebApplication" data-throw-if-not-resolved="False" />
  name: Web
  description: |+
    Specifies settings for a web application.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: AzureAD.Set-AzureADMSApplication
name: Set-AzureADMSApplication
description: |-
  Updates the properties of an application object.
metadata:
  external help file: Microsoft.Open.MS.GraphV10.PowerShell.dll-Help.xml
  Module Name: AzureAD
  online version: ""
  schema: 2.0.0
