### YamlMime:PowershellCmdlet
summary: |-
  Gets the directory synchronization settings.
module: MSOnline
notes: ""
links:
- text: Set-MsolDirSyncConfiguration
  href: ./Set-MsolDirSyncConfiguration.yml
syntaxes:
- Get-MsolDirSyncConfiguration [-TenantId <Guid>] [<CommonParameters>]
parameters:
- type: <xref href="Guid" data-throw-if-not-resolved="False" />
  name: TenantId
  description: |+
    Specifies the unique ID of the tenant on which to perform the operation.
    The default value is the tenant of the current user.
    This parameter applies only to partner users.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: MSOnline.Get-MsolDirSyncConfiguration
name: Get-MsolDirSyncConfiguration
description: |-
  The **Get-MsolDirSyncConfiguration** cmdlet gets the directory synchronization settings.
metadata:
  external help file: Microsoft.Online.Administration.Automation.PSModule.dll-Help.xml
  online version: ""
  schema: 2.0.0
  ms.assetid: 174960FD-00BB-461F-B8C9-DDA519E24F00
  ms.reviewer: rodejo
  ms.custom: iamfeature=PowerShell
