### YamlMime:PowershellCmdlet
summary: |-
  Modifies the directory synchronization settings.
module: MSOnline
notes: ""
links:
- text: Get-MsolDirSyncConfiguration
  href: ./Get-MsolDirSyncConfiguration.yml
syntaxes:
- >-
  Set-MsolDirSyncConfiguration -AccidentalDeletionThreshold <UInt32> [-Force] [-TenantId <Guid>]

   [<CommonParameters>]
parameters:
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: AccidentalDeletionThreshold
  isRequired: true
  description: |+
    Specifies the accidental deletion threshold.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Forces the command to run without asking for user confirmation.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Guid" data-throw-if-not-resolved="False" />
  name: TenantId
  description: |+
    Specifies the unique ID of the tenant on which to perform the operation.
    The default value is the tenant of the current user.
    This parameter applies only to partner users.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: MSOnline.Set-MsolDirSyncConfiguration
name: Set-MsolDirSyncConfiguration
description: |-
  The **Set-MsolDirSyncConfiguration** cmdlet modifies the directory synchronization settings.
metadata:
  external help file: Microsoft.Online.Administration.Automation.PSModule.dll-Help.xml
  online version: ""
  schema: 2.0.0
  ms.assetid: 66F7F0D7-A464-4E72-971F-73E3DFF04A70
  ms.reviewer: rodejo
  ms.custom: iamfeature=PowerShell
