### YamlMime:PowershellCmdlet
summary: |-
  Creates an extension property on an application object.
module: AzureADPreview
notes: ""
inputs:
- name: <xref href="string" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="System.String" data-throw-if-not-resolved="False" /><span>]</span>
  description: ""
outputs:
- name: <xref href="Microsoft.Open.MSGraph.Model.ExtensionProperty" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  New-AzureADMSApplicationExtensionProperty -ObjectId <String> [-Name <String>] [-DataType <String>]

   [-TargetObjects <System.Collections.Generic.List`1[System.String]>] [<CommonParameters>]
examples:
- title: 'Example 1: Create an extension property'
  code: |-
    PS C:\>New-AzureADMSApplicationExtensionProperty -ObjectId "3ddd22e7-a150-4bb3-b100-e410dea1cb84" -DataType "string" -Name "NewAttribute" -TargetObjects "Application"


              ObjectId                             Name                                                    TargetObjects
              --------                             ----                                                    -------------
              3ddd22e7-a150-4bb3-b100-e410dea1cb84 extension_36ee4c6c081240a2b820b22ebd02bce3_NewAttribute {}
  description: |-
    This command creates an application extension property of the string type for the specified object.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DataType
  description: |+
    Specifies the data type of the extension property.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Name
  description: |+
    Specifies the data type of the extension property.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    The unique identifier of the object specific Azure Active Directory object

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="System.String" data-throw-if-not-resolved="False" /><span>]</span>
  name: TargetObjects
  description: |+
    Specifies target objects.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: AzureADPreview.New-AzureADMSApplicationExtensionProperty
name: New-AzureADMSApplicationExtensionProperty
description: |-
  Creates an extension property on an application object.
metadata:
  external help file: Microsoft.Open.MS.GraphBeta.PowerShell.dll-Help.xml
  Module Name: AzureADPreview
  online version: ""
  schema: 2.0.0
