### YamlMime:PowershellCmdlet
summary: |-
  Creates an application.
module: AzureADPreview
notes: ""
links:
- text: Get-AzureADApplication
  href: ./Get-AzureADApplication.yml
- text: Remove-AzureADApplication
  href: ./Remove-AzureADApplication.yml
- text: Set-AzureADApplication
  href: ./Set-AzureADApplication.yml
- text: Get-AzureADApplication
  href: ./Get-AzureADApplication.yml
- text: Remove-AzureADApplication
  href: ./Remove-AzureADApplication.yml
- text: Set-AzureADApplication
  href: ./Set-AzureADApplication.yml
syntaxes:
- >-
  New-AzureADApplication [-AddIns <System.Collections.Generic.List`1[Microsoft.Open.AzureAD.Model.AddIn]>]

   [-AllowGuestsSignIn <Boolean>] [-AllowPassthroughUsers <Boolean>] [-AppLogoUrl <String>]

   [-AppRoles <System.Collections.Generic.List`1[Microsoft.Open.AzureAD.Model.AppRole]>]

   [-AvailableToOtherTenants <Boolean>] -DisplayName <String> [-ErrorUrl <String>]

   [-GroupMembershipClaims <String>] [-Homepage <String>]

   [-IdentifierUris <System.Collections.Generic.List`1[System.String]>] [-InformationalUrls <InformationalUrl>]

   [-IsDeviceOnlyAuthSupported <Boolean>] [-IsDisabled <Boolean>]

   [-KeyCredentials <System.Collections.Generic.List`1[Microsoft.Open.AzureAD.Model.KeyCredential]>]

   [-KnownClientApplications <System.Collections.Generic.List`1[System.String]>] [-LogoutUrl <String>]

   [-Oauth2AllowImplicitFlow <Boolean>] [-Oauth2AllowUrlPathMatching <Boolean>]

   [-Oauth2Permissions <System.Collections.Generic.List`1[Microsoft.Open.AzureAD.Model.OAuth2Permission]>]

   [-Oauth2RequirePostResponse <Boolean>] [-OrgRestrictions <System.Collections.Generic.List`1[System.String]>]

   [-OptionalClaims <OptionalClaims>] [-ParentalControlSettings <ParentalControlSettings>]

   [-PasswordCredentials <System.Collections.Generic.List`1[Microsoft.Open.AzureAD.Model.PasswordCredential]>]

   [-PreAuthorizedApplications <System.Collections.Generic.List`1[Microsoft.Open.AzureAD.Model.PreAuthorizedApplication]>]

   [-PublicClient <Boolean>] [-PublisherDomain <String>] [-RecordConsentConditions <String>]

   [-ReplyUrls <System.Collections.Generic.List`1[System.String]>]

   [-RequiredResourceAccess <System.Collections.Generic.List`1[Microsoft.Open.AzureAD.Model.RequiredResourceAccess]>]

   [-SamlMetadataUrl <String>] [-SignInAudience <String>] [-WwwHomepage <String>] [<CommonParameters>]
examples:
- title: 'Example 1: Create an application'
  code: |-
    PS C:\>New-AzureADApplication -DisplayName "My new application"  -IdentifierUris "http://mynewapp.contoso.com"

    ObjectId                             AppId                                DisplayName 
    --------                             -----                                ----------- 
    acd10942-5747-4385-8824-4c5d5fa904f9 b5fecfab-0ea2-4fd1-8570-b2c41b3d5149 My new application
  description: |-
    This command creates an application in Azure AD.
  summary: ""
parameters:
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.AzureAD.Model.AddIn" data-throw-if-not-resolved="False" /><span>]</span>
  name: AddIns
  description: |+
    Defines custom behavior that a consuming service can use to call an app in specific contexts. For example, applications that can render file streams may set the addIns property for its "FileHandler" functionality. This will let services like Office 365 call the application in the context of a document the user is working on.


  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: AllowGuestsSignIn
  description: |+
    {{ Fill AllowGuestsSignIn Description }}

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: AllowPassthroughUsers
  description: |+
    {{ Fill AllowPassthroughUsers Description }}

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: AppLogoUrl
  description: |+
    {{ Fill AppLogoUrl Description }}

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.AzureAD.Model.AppRole" data-throw-if-not-resolved="False" /><span>]</span>
  name: AppRoles
  description: |+
    The collection of application roles that an application may declare. These roles can be assigned to users, groups or service principals.


  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: AvailableToOtherTenants
  description: |+
    Indicates whether this application is available in other tenants.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DisplayName
  isRequired: true
  description: |+
    Specifies the display name of the application.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ErrorUrl
  description: |+
    The Error URL of this application

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: GroupMembershipClaims
  description: |+
    A bitmask that configures the "groups" claim issued in a user or OAuth 2.0 access token that the application expects. The bitmask values are: 0: None, 1: Security groups and Azure AD roles, 2: Reserved, and 4: Reserved. Setting the bitmask to 7 will get all of the security groups, distribution groups, and Azure AD directory roles that the signed-in user is a member of.


  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Homepage
  description: |+
    The URL to the application's homepage.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="System.String" data-throw-if-not-resolved="False" /><span>]</span>
  name: IdentifierUris
  description: |+
    User-defined URI(s) that uniquely identify a Web application within its Azure AD tenant, or within a verified custom domain (see "Domains" tab in the Azure classic portal) if the application is multi-tenant. 

    The first element is populated from the Web application's "APP ID URI" field if updated via the Azure classic portal (or respective Azure AD PowerShell cmdlet parameter). Additional URIs can be added via the application manifest; see Understanding the Azure AD Application Manifest for details. This collection is also used to populate the Web application's servicePrincipalNames collection. 

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="InformationalUrl" data-throw-if-not-resolved="False" />
  name: InformationalUrls
  description: |+
    {{ Fill InformationalUrls Description }}

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: IsDeviceOnlyAuthSupported
  description: |+
    {{ Fill IsDeviceOnlyAuthSupported Description }}

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: IsDisabled
  description: |+
    {{ Fill IsDisabled Description }}

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.AzureAD.Model.KeyCredential" data-throw-if-not-resolved="False" /><span>]</span>
  name: KeyCredentials
  description: |+
    The collection of key credentials associated with the application

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="System.String" data-throw-if-not-resolved="False" /><span>]</span>
  name: KnownClientApplications
  description: |+
    Client applications that are tied to this resource application. Consent to any of the known client applications will result in implicit consent to the resource application through a combined consent dialog (showing the OAuth permission scopes required by the client and the resource).

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: LogoutUrl
  description: |+
    The logout url for this application


  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: Oauth2AllowImplicitFlow
  description: |+
    Specifies whether this web application can request OAuth2.0 implicit flow tokens. The default is false.


  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: Oauth2AllowUrlPathMatching
  description: |+
    Specifies whether, as part of OAuth 2.0 token requests, Azure AD will allow path matching of the redirect URI against the application's replyUrls. The default is false.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.AzureAD.Model.OAuth2Permission" data-throw-if-not-resolved="False" /><span>]</span>
  name: Oauth2Permissions
  description: |+
    The collection of OAuth 2.0 permission scopes that the web API (resource) application exposes to client applications. These permission scopes may be granted to client applications during consent.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: Oauth2RequirePostResponse
  description: |+
    Set this to true if an Oauth2 psot response is required 

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="OptionalClaims" data-throw-if-not-resolved="False" />
  name: OptionalClaims
  description: |+
    {{ Fill OptionalClaims Description }}

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="System.String" data-throw-if-not-resolved="False" /><span>]</span>
  name: OrgRestrictions
  description: |+
    {{ Fill OrgRestrictions Description }}

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="ParentalControlSettings" data-throw-if-not-resolved="False" />
  name: ParentalControlSettings
  description: |+
    {{ Fill ParentalControlSettings Description }}

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.AzureAD.Model.PasswordCredential" data-throw-if-not-resolved="False" /><span>]</span>
  name: PasswordCredentials
  description: |+
    The collection of password credentials associated with the application.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.AzureAD.Model.PreAuthorizedApplication" data-throw-if-not-resolved="False" /><span>]</span>
  name: PreAuthorizedApplications
  description: |+
    {{ Fill PreAuthorizedApplications Description }}

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: PublicClient
  description: |+
    Specifies whether this application is a public client (such as an installed application running on a mobile device). Default is false.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: PublisherDomain
  description: |+
    {{ Fill PublisherDomain Description }}

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: RecordConsentConditions
  description: |+
    Do not use. May be removed in future versions 

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="System.String" data-throw-if-not-resolved="False" /><span>]</span>
  name: ReplyUrls
  description: |+
    Specifies the URLs that user tokens are sent to for sign in, or the redirect URIs that OAuth 2.0 authorization codes and access tokens are sent to.


  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Collections.Generic.List`1" data-throw-if-not-resolved="False" /><span>[</span><xref href="Microsoft.Open.AzureAD.Model.RequiredResourceAccess" data-throw-if-not-resolved="False" /><span>]</span>
  name: RequiredResourceAccess
  description: |+
    Specifies resources that this application requires access to and the set of OAuth permission scopes and application roles that it needs under each of those resources. This pre-configuration of required resource access drives the consent experience.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SamlMetadataUrl
  description: |+
    The URL to the SAML metadata for the application.


  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SignInAudience
  description: |+
    {{ Fill SignInAudience Description }}

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: WwwHomepage
  description: |+
    {{ Fill WwwHomepage Description }}

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: AzureADPreview.New-AzureADApplication
name: New-AzureADApplication
description: |-
  The **New-AzureADApplication** cmdlet creates an application in Azure Active Directory (AD).
metadata:
  external help file: Microsoft.Open.AzureAD16.Graph.PowerShell.dll-Help.xml
  Module Name: AzureADPreview
  ms.assetid: 235D5FBC-E726-4F95-8BBD-454E8180576A
  ms.custom: iamfeature=PowerShell
  ms.reviewer: stevemutungi
  online version: ""
  schema: 2.0.0
