### YamlMime:PowershellCmdlet
summary: |-
  Removes an owner from an application object.
module: AzureADPreview
notes: ""
inputs:
- name: <xref href="string" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- Remove-AzureADMSApplicationOwner -ObjectId <String> -OwnerId <String> [<CommonParameters>]
examples:
- title: 'Example 1: Remove an owner from an application'
  code: |-
    PS C:\>Remove-AzureADMSApplicationOwner -ObjectId "3ddd22e7-a150-4bb3-b100-e410dea1cb84" -OwnerId "c13dd34a-492b-4561-b171-40fcce2916c5"
  description: |-
    This command removes the owner from the specified application.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    Specifies the ID of an application in Azure AD.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: OwnerId
  isRequired: true
  description: |+
    Specifies the ID of the owner.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: AzureADPreview.Remove-AzureADMSApplicationOwner
name: Remove-AzureADMSApplicationOwner
description: |-
  Removes an owner from an application object.
metadata:
  external help file: Microsoft.Open.MS.GraphBeta.PowerShell.dll-Help.xml
  Module Name: AzureADPreview
  online version: ""
  schema: 2.0.0
